#数据源配置
spring:
  datasource:
    username: root
    password: Root
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver


#redis配置
  redis:
    #服务器地址
    host: 172.30.1.44
    #端口
    port: 6379
    #默认操作的数据库
    database: 1
    #连接超时
    connect-timeout: 10000ms

    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认未8
        max-idle: 200
        #最小空闲连接,默认未0，
        min-idle: 5
  rabbitmq:
    host: 172.30.1.44
    username: guest
    password: guest
    #虚拟主机
    virtual-host: /
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息，处理完在继续下一条消息
        prefetch: 1
        #启动时是否启动容器，默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #重试最大间隔时间，默认1000ms
        max-interval: 1000ms
        #重试的间隔层数，比如配2.0 ，第一次10s,第二次20s,第三次40s
        multiplier: 1





#Mybatis-plus配置
mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.zyd.seckill.entity
  configuration:
    map-underscore-to-camel-case: true
#MaBatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包


logging:
  level:
    com.jd.mapper: debug



