#数据源配置
spring:
  datasource:
    username: root
    password: Root
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver


#redis配置
  redis:
    #服务器地址
    host: 192.168.101.119
    #端口
    port: 6379
    #默认操作的数据库
    database: 1
    #连接超时
    connect-timeout: 10000ms

    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认未8
        max-idle: 200
        #最小空闲连接,默认未0，
        min-idle: 5





#Mybatis-plus配置
mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.zyd.seckill.entity
  configuration:
    map-underscore-to-camel-case: true
#MaBatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包


logging:
  level:
    com.jd.mapper: debug



